### ISSUE TITLE
Problem while installing

### ISSUE THREAD

**Issue by rphellan** [cozygene/SLIViT#1]
While installing SLIViT requirements, I got the message ERROR: Could not find a version that satisfies the requirement numpy<3.0.0,>=2.0.0 .

The requirements for SLIViT include **fastai**, which requires **spacy**, which contains the line of code `numpy>=2.0.0; python_version < "3.9"` in its requirements.txt file, which leads to a bug (numpy 2.0.0 requires python 3.9, but SLIViT is suggested to be installed with python 3.8).

Can you suggest a quick workaround?

Actually, switching to python 3.9 in `conda create --name slivit python=3.9` seems to work.

Running `python evaluate.py -h` works, but with the error message below:

```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\...\Documents\Slivit\SLIViT\evaluate.py", line 1, in <module>
    from auxiliaries.misc import *
  File "C:\Users\...\Documents\Slivit\SLIViT\auxiliaries\misc.py", line 1, in <module>
    import torch
...
```

My fixes were:
pip install fastai==2.7.18
pip install torchvision==0.20.0
pip install --upgrade torch
pip install --upgrade scikit-image

**Comment by naiQAQian** [comment]
Thanks
